### ISSUE TITLE
mysql module panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by jostreff** [netdata/go.d.plugin#325]
My configuration have into conf.d/go.d/mysql.conf

```yaml
jobs:
  - name: local
    dsn: netdata@tcp(127.0.0.1:3306)/

  - name: local
    dsn: root@tcp(10.97.152.5:3306)/ 

  - name: local
    dsn: root@/

  - name: local
    dsn: root@unix(/var/run/mysqld/mysqld.sock)/
```

because mysql is bind only to specific IP address of the machine into specific freebsd fib. 

```bash
cat /usr/local/etc/my.cnf 
[mysqld]
bind-address=10.97.152.5
```

The error which popups is:

```bash
% /usr/local/libexec/netdata/plugins.d/go.d.plugin -d -c /usr/local/lib/netdata/conf.d/ -m mysql
[ INFO  ] main[main] setup.go:91 maximum number of used CPUs 32
[ INFO  ] main[main] setup.go:94 minimum update every 1
[ INFO  ] main[main] create.go:71 loading 'mysql' configuration
[ ERROR ] mysql[local] mysql.go:80 error on pinging the mysql database [netdata@tcp(127.0.0.1:3306)/]: dial tcp 127.0.0.1:3306: connect: connection refused
[ ERROR ] mysql[local] mysql.go:61 dial tcp 127.0.0.1:3306: connect: connection refused
[ ERROR ] mysql[local] job.go:116 Init failed
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x88df9e]

goroutine 8 [running]:
sync.(*Mutex).Lock(...)
        /home/travis/.gimme/versions/go1.13.linux.amd64/src/sync/mutex.go:74
database/sql.(*DB).Close(0x0, 0xc0002b8308, 0xc0002c8000)
        /home/travis/.gimme/versions/go1.13.linux.amd64/src/database/sql/sql.go:810 +0x3e
github.com/netdata/go.d.plugin/modules/mysql.(*MySQL).Cleanup(0xc0001690e0)
        /home/travis/gopath/src/github.com/netdata/go.d.plugin/modules/mysql/mysql.go:47 +0x33
github.com/netdata/go-orchestrator/module.(*Job).AutoDetection.func1(0xc000093de8, 0xc00023a0e0)
        /home/travis/gopath/pkg/mod/github.com/netdata/go-orchestrator@v0.0.0-20190905093727-c793edba0e8f/module/job.go:111 +0x69
github.com/netdata/go-orchestrator/module.(*Job).AutoDetection(0xc00023a0e0, 0xc0000cce00)
        /home/travis/gopath/pkg/mod/github.com/netdata/go-orchestrator@v0.0.0-20190905093727-c793edba0e8f/module/job.go:118 +0x25c
github.com/netdata/go-orchestrator.(*Orchestrator).startOnce(0xc00023a000, 0x11710e0, 0xc00023a0e0, 0xc000093eb0)
        /home/travis/gopath/pkg/mod/github.com/netdata/go-orchestrator@v0.0.0-20190905093727-c793edba0e8f/start.go:27 +0xa2
github.com/netdata/go-orchestrator.(*Orchestrator).jobStartLoop(0xc00023a000)
        /home/travis/gopath/pkg/mod/github.com/netdata/go-orchestrator@v0.0.0-20190905093727-c793edba0e8f/start.go:15 +0xb9
created by github.com/netdata/go-orchestrator.(*Orchestrator).Serve
        /home/travis/gopath/pkg/mod/github.com/netdata/go-orchestrator@v0.0.0-20190905093727-c793edba0e8f/orchestrator.go:109 +0xaa
```

**Comment by ilyam8** [comment]
@jostreff thx for reporting!

**Comment by ilyam8** [comment]
the fix will be in the next release early next week
